from PyQt5.QtWidgets import QMainWindow, QApplication
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from explanation_component import ExplanationComponent
from inference_engine import InferenceEngine
from knowledge_base import KnowledgeBase

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.knowledge_base = KnowledgeBase()
        self.inference_engine = InferenceEngine(self.knowledge_base.list_nodes)
        self.explanation_component = ExplanationComponent()
        self.fill_combobox()

        self.comboBox.currentTextChanged.connect(self.get_answer_1)
        self.comboBox_3.currentTextChanged.connect(self.get_answer_2)
        self.comboBox_4.currentTextChanged.connect(self.get_answer_2)
        self.comboBox_6.currentTextChanged.connect(self.get_answer_3)
        self.comboBox_7.currentTextChanged.connect(self.get_answer_3)
        self.comboBox_2.currentTextChanged.connect(self.get_answer_4)
        self.comboBox_5.currentTextChanged.connect(self.get_answer_4)

    # наполняем ui значениями, используя методы дял поиска узлов из класса KnowledgeBase
    def fill_combobox(self):
        pet_nodes = self.knowledge_base.find_nodes_by_output('Питомец', 'IS-A')
        for pet in pet_nodes:
            self.comboBox.addItem(pet.name)
            self.comboBox_3.addItem(pet.name)
            self.comboBox_7.addItem(pet.name)

        characteristics = self.knowledge_base.find_nodes_by_connection('has-characteristic', 'input')
        for char in characteristics:
            self.comboBox_4.addItem(char.name)

        habitat_list = self.knowledge_base.find_nodes_by_connection('is-need', 'input')
        for habitat in habitat_list:
            self.comboBox_6.addItem(habitat.name)

        requirements = self.knowledge_base.find_nodes_by_output('Критерии выбора')
        for req in requirements:
            self.comboBox_2.addItem(req.name)

        requirements2 = self.knowledge_base.find_nodes_by_connection('has-value', 'output')
        for req in requirements2:
            self.comboBox_5.addItem(req.name)

    def log(self, log):
        self.textBrowser.clear()
        self.textBrowser.append(log)

    def get_answer_1(self):
        self.inference_engine.used = []
        nodes = self.inference_engine.budget_request(self.comboBox.currentText())
        answer = f'Для питомца "{self.comboBox.currentText()}" требуется бюджет: \n'
        answer += '\n:'.join(nodes)
        self.log(answer)

    def get_answer_2(self):
        self.inference_engine.used = []
        answer = f'Имеет ли "{self.comboBox_3.currentText()}" свойство "{self.comboBox_4.currentText()}"? \n'
        answer += str(self.inference_engine.pet_characteristic_request(self.comboBox_3.currentText(),
                                                                   self.comboBox_4.currentText()))
        self.log(answer)

    def get_answer_3(self):
        self.inference_engine.used = []
        answer = f'Среда обитания "{self.comboBox_6.currentText()}" необходима питомцу"{self.comboBox_7.currentText()}"? \n'
        answer += str(self.inference_engine.pet_characteristic_request(self.comboBox_7.currentText(),
                                                                    self.comboBox_6.currentText()))
        self.log(answer)

    def get_answer_4(self):
        self.inference_engine.used = []
        answer = f'"{self.comboBox_2.currentText()}" является "{self.comboBox_5.currentText()}"? \n'
        answer += str(self.inference_engine.requirements_request(self.comboBox_2.currentText(),
                                                                    self.comboBox_5.currentText()))
        self.log(answer)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 416)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(440, 70, 321, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 30, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(40, 231, 741, 141))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 391, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(770, 70, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(50, 190, 350, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(770, 190, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 110, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(130, 110, 221, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(360, 110, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(440, 110, 321, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(770, 110, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(410, 190, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(490, 190, 271, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(50, 150, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(190, 150, 221, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(420, 150, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setGeometry(QtCore.QRect(530, 150, 231, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setObjectName("comboBox_7")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(770, 150, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Семантическая сеть"))
        self.label_2.setText(_translate("MainWindow", "Какой бюджет в месяц требуется для питомца"))
        self.label_3.setText(_translate("MainWindow", "?"))
        self.label_5.setText(_translate("MainWindow", "?"))
        self.label_6.setText(_translate("MainWindow", "Имеет ли "))
        self.label_7.setText(_translate("MainWindow", "свойство"))
        self.label_8.setText(_translate("MainWindow", "?"))
        self.label_9.setText(_translate("MainWindow", "является"))
        self.label_10.setText(_translate("MainWindow", "Среда обитания"))
        self.label_11.setText(_translate("MainWindow", "необходима"))
        self.label_12.setText(_translate("MainWindow", "?"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MainWindow()
    ex.show()
    sys.exit(app.exec_())